version: 2.1

jobs:
  install:
    parameters:
      node-version:
        type: string
        default: '14.18.0'
      resource-class:
        type: enum
        enum:
          - small
          - medium
          - large
    docker:
      - image: cimg/node:<< parameters.node-version >>
    resource_class: << parameters.resource-class >>
    steps:
      - checkout
      - run: |
          npm i

workflows:
  main:
    jobs:
      - install:
          matrix:
            parameters:
              resource-class:
                - medium
                - large
